# Generated by Django 5.2.2 on 2026-03-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinquiry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact Inquiry', 'verbose_name_plural': 'Contact Inquiries'},
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, help_text='Mark as read when you review this inquiry', verbose_name='Read Status'),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='email',
            field=models.EmailField(help_text='Enter a valid email address', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='inquiry_type',
            field=models.CharField(choices=[('quote', 'Request a Quote'), ('technical', 'Technical Support'), ('custom', 'Custom Cable Solutions'), ('other', 'Other')], help_text='Select the type of your inquiry', max_length=20, verbose_name='Inquiry Type'),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='message',
            field=models.TextField(help_text='Describe your requirements in detail', verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='name',
            field=models.CharField(help_text='Enter your full name', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='phone',
            field=models.CharField(blank=True, help_text='Enter your phone number (optional)', max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='subject',
            field=models.CharField(help_text='Brief description of your inquiry', max_length=200, verbose_name='Subject'),
        ),
        migrations.AddIndex(
            model_name='contactinquiry',
            index=models.Index(fields=['-created_at'], name='contact_con_created_1abdc3_idx'),
        ),
        migrations.AddIndex(
            model_name='contactinquiry',
            index=models.Index(fields=['is_read', '-created_at'], name='contact_con_is_read_647504_idx'),
        ),
    ]
