# Generated by Django 5.2.2 on 2026-03-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactinquiry_options_contactinquiry_is_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinquiry',
            name='inquiry_type',
            field=models.CharField(choices=[('quote', 'Request a Quote'), ('technical', 'Technical Support'), ('custom', 'Custom Cable Solutions'), ('partnership', 'Partnership Inquiry'), ('general', 'General Inquiry'), ('other', 'Other')], help_text='Select the type of your inquiry', max_length=20, verbose_name='Inquiry Type'),
        ),
    ]
