# Generated by Django 5.2.2 on 2025-08-22 10:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='certificates'),
        ),
    ]
