# Generated by Django 5.2.2 on 2025-06-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LadderPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('thickness', models.FloatField()),
                ('side', models.FloatField()),
                ('dim', models.FloatField()),
                ('price_final', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TrayPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('thickness', models.FloatField()),
                ('dim', models.FloatField()),
                ('price_with_joints', models.FloatField()),
            ],
        ),
    ]
