# Generated by Django 5.2.2 on 2025-07-15 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_teammember_delete_ladderprice_delete_trayprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
