# Generated by Django 5.2.2 on 2025-07-15 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
