# Generated by Django 5.2.2 on 2025-07-15 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_testimonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
