# Generated by Django 5.2.2 on 2025-08-13 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_userdata_delete_teammember'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
