# Generated by Django 5.2.2 on 2025-08-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('facility', 'Manufacturing Facility'), ('products', 'Cable Solutions')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='about/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
